config/routes.rb
BackChannelAppProject::Application.routes.draw do
    get "posts/vote"
    post "posts/createreply"
    get "posts/reply"
    post "posts/search"
    get "posts/index"
    post "posts/create"
    post "posts/vote"
    post "users/create"
  resources :posts, :member => {:search => :post, :reply => :get, :createreply => :post, :vote => :post}
  resources :logins

  resources :replies

  resources :votes

  resources :users

  root :to => 'logins#index'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  has_one:user

  validates :reply, :presence => true

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.json
  #We doesnt use this Controller.
  def index
    @replies = Reply.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @reply = Reply.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply])

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :postId %><br />
    <%= f.text_field :postId %>
    </div>
  <div class="field">
    <%= f.label :reply %><br />
    <%= f.text_area :reply %>
  </div>
  <div class="field">
    <%= f.hidden_field :repliedUser, :value=>session[:userName]  %>
  </div>
    <div class="field">
    <%= f.hidden_field :repliedUser, :value=>session[:userName]  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', posts_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Postid</th>
    <th>Reply</th>
    <th>Replieduser</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.postId %></td>
    <td><%= reply.reply %></td>
    <td><%= reply.repliedUser %></td>
    <td><%= link_to 'Show', reply %></td>
    <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <td><%= link_to 'Destroy', reply, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Postid:</b>
  <%= @reply.postId %>
</p>

<p>
  <b>Reply:</b>
  <%= @reply.reply %>
</p>

<p>
  <b>Replieduser:</b>
  <%= @reply.repliedUser %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>