config/routes.rb
BackChannelAppProject::Application.routes.draw do
    get "posts/vote"
    post "posts/createreply"
    get "posts/reply"
    post "posts/search"
    get "posts/index"
    post "posts/create"
    post "posts/vote"
    post "users/create"
  resources :posts, :member => {:search => :post, :reply => :get, :createreply => :post, :vote => :post}
  resources :logins

  resources :replies

  resources :votes

  resources :users

  root :to => 'logins#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.json
  #This method is to show the login screen with sessions cleared.
  def index
    session[:userName] = nil
    session[:role]= nil
    @adminCheck = User.find_by_role("admin")
    if(@adminCheck == nil)
    @admin=User.new(:userName=> "adminaccount", :password=>"admin123",:unityId=>"admin123",:emailAddress=>"admin@gmail.com",:role=>"admin")
    @admin.save
      end
    end


  # POST /logins
  # POST /logins.json
  #This method is for Authenticating the User, First we check whether the User exists with the username entered in login page.
  #If there isnt any record found we are redirecting the User to Login screen with a proper error msg.
  #If a record exists whether the password matches with the password stored in DB and the role as well.
  #On success we redirect to the Posts/index if not then Login screen.
  def create
  @user= User.find_by_userName(params[:name])
  if(@user == nil)
      flash[:notice] = "Incorrect Username/Password"
       redirect_to(:controller => "logins", :action => "index")

    else if(params[:password]!= 'nil' && @user.password == params[:password] && @user.role == "user")
      session[:userName]=@user.userName
      session[:id]=@user.id
      session[:role]="user"
      redirect_to(:controller => "posts", :action => "index")
    else if(params[:password]!= 'nil' && @user.password == params[:password] && @user.role == "admin")
        session[:userName]=@user.userName
      session[:id]=@user.id
      session[:role]="admin"
      redirect_to(:controller => "posts", :action => "index")
     else
      flash[:notice] = "Incorrect Username/Password"
      redirect_to(:controller => "logins", :action => "index")
      end
    end
    end

 # This method is to edit, which we are not gonna use here.
  def edit
     #@logins = Login.all
     session[:userName] = nil
       session[:id]= nil
       redirect_to(:controller => "logins", :action => "index")
    #logout();
  end

  #This method is for signout where we clear the sessions.
    def signOut
       session[:userName] = nil
       session[:id]= nil
       session[:role]= nil
       redirect_to(:controller => "logins", :action => "index")

    end
    end


end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<fieldset>
  <legend>Please Log In</legend>
  <%= form_tag :url => 'login/create' %>
   <p>
  <label for="name">UserName:</label>
  <%= text_field_tag :name %>
  </p>

  <p>
   <label for="password">Password:</label>
   <%= password_field_tag :password%>
   </p>
  <p id="notice" style="color: red"><%= notice %></p>

   <p>
    <%= submit_tag "Login" %>
    </p>

  <%= link_to 'Create an account', new_user_path %>

   </fieldset>

  </div>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>