config/routes.rb
BackChannelAppProject::Application.routes.draw do
    get "posts/vote"
    post "posts/createreply"
    get "posts/reply"
    post "posts/search"
    get "posts/index"
    post "posts/create"
    post "posts/vote"
    post "users/create"
  resources :posts, :member => {:search => :post, :reply => :get, :createreply => :post, :vote => :post}
  resources :logins

  resources :replies

  resources :votes

  resources :users

  root :to => 'logins#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many:posts
  has_many:replies


  validates :unityId, :presence => true, :uniqueness => true
  validates :userName, :presence => true, :length => {:minimum => 6, :maximum => 30}
  validates :password, :presence => true, :length => {:minimum => 6, :maximum => 30}
  validates :emailAddress, :presence => true, :length => {:minimum => 6, :maximum => 20}
  validates :role,:presence => true
  validates_presence_of :userName
  validates_uniqueness_of :userName
  validates_confirmation_of :password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  #this is to check the session hence we redirect to application controller, authorize method.
  #before_filter :authorize, :except => :new
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    #if(session[:userName]=='nil')
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }

      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
   if @user.update_attribute(:userName,"anonymous")
      format.html { redirect_to users_path, notice: 'User was successfully deleted.' }
      format.json { head :ok }
    end
  end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userName %><br />
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :unityId %><br />
    <%= f.text_field :unityId %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password%>
  </div>
  <div class="field">
    <%= f.label :emailAddress %><br />
    <%= f.text_field :emailAddress %>
  </div>
  <div class="field">
     <%= f.label :role %><br />
    <% if((session[:userName] != nil) and (session[:role] != nil))%>
        <%= f.select :role, [['admin','admin'],['user','user']] %>
    <% else %>
        <%= f.select :role, [['user','user']] %>
    <% end %>
    </div>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

 <% if(session[:role] == 'admin') %>
   <%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
    <% else %>
   <%= link_to 'Login Page', logins_path %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>
   <p id="notice" style="color: red"><%= notice %></p>
<table border="1">
  <tr>
    <th>Username</th>
    <th>Unityid</th>
    <th>Emailaddress</th>
    <th>Role</th>
    <th>Links</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <% if(user.userName != 'anonymous') %>
   <td><%= user.userName %></td>
    <td><%= user.unityId %></td>
    <td><%= user.emailAddress %></td>
    <td><%= user.role %></td>

        <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if(user.userName != 'adminaccount') %>
    <td><%= button_to "delete", user, :method=>:delete, :class=>:destroy %></td>
            <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New User', new_user_path %>
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>
<br>


<% if(session[:role] == 'admin') %>
   <%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
    <% else %>
   <%= link_to 'Login Page', logins_path %>
<% end %>    

app/views/users/show.html.erb
<br>
<p id="notice" style="color: green;"><%= notice %></p>
  <br>

<p>
  <b>Username:</b>
  <%= @user.userName %>
</p>

<p>
  <b>Unityid:</b>
  <%= @user.unityId %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Emailaddress:</b>
  <%= @user.emailAddress %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<% if(session[:role] == 'admin') %>
   <%= link_to 'See posts', posts_path %>
    <% else %>
   <%= link_to 'Login Page', logins_path %>
<% end %>